import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { compile } from "json-schema-to-typescript";

const repository = resolve(fileURLToPath(new URL("..", import.meta.url)));
const check = process.argv.slice(2).includes("--check");
const generated = resolve(repository, "packages/runtime/src/generated");

const requestSchema = await readJson("schemas/browser-request-v1.schema.json");
const responseSchema = await readJson("schemas/browser-response-v1.schema.json");

const requestTypes = await compile(requestSchema, "BrowserRequest", typeOptions());
const responseTypes = await compile(responseSchema, "BrowserResponse", typeOptions());
const validators = compileValidators(requestSchema, responseSchema);

if (!check) {
  await mkdir(generated, { recursive: true });
}
await publish("browser-request.ts", requestTypes);
await publish("browser-response.ts", responseTypes);
await publish("validators.js", validators);
await publish("validators.d.ts", validatorDeclarations());
await publish("codec.ts", codecSource());

async function readJson(relative) {
  return JSON.parse(await readFile(resolve(repository, relative), "utf8"));
}

function typeOptions() {
  return {
    additionalProperties: false,
    bannerComment:
      "// Generated by `cargo xtask schema`; edit Rust protocol types instead.\n",
    cwd: repository,
    enableConstEnums: false,
    style: {
      bracketSpacing: true,
      printWidth: 100,
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: "all",
      useTabs: false,
    },
    unknownAny: false,
  };
}

function compileValidators(request, response) {
  const ajv = new Ajv2020({
    allErrors: true,
    code: { esm: true, lines: true, source: true },
    // Numeric ranges are explicit in the schemas; these names register the
    // non-asserting format labels emitted by schemars.
    formats: { uint16: true, uint32: true, uint64: true },
    strict: true,
  });
  ajv.compile(request);
  ajv.compile(response);
  const source = standaloneCode(ajv, {
    validateBrowserRequest: request.$id,
    validateBrowserResponse: response.$id,
  });
  return `// Generated by \`cargo xtask schema\`; do not edit.\n${source}`;
}

function validatorDeclarations() {
  return `// Generated by \`cargo xtask schema\`; do not edit.
export interface ValidationError {
  readonly instancePath: string;
  readonly keyword: string;
  readonly message?: string;
}

export interface ProtocolValidator {
  (value: unknown): boolean;
  readonly errors?: readonly ValidationError[] | null;
}

export const validateBrowserRequest: ProtocolValidator;
export const validateBrowserResponse: ProtocolValidator;
`;
}

function codecSource() {
  return `// Generated by \`cargo xtask schema\`; do not edit.
import type { BrowserRequest } from "./browser-request.js";
import type { BrowserResponse } from "./browser-response.js";
import {
  validateBrowserRequest,
  validateBrowserResponse,
  type ProtocolValidator,
} from "./validators.js";

export class ProtocolDecodeError extends Error {
  readonly issues: readonly string[];

  constructor(message: string, issues: readonly string[]) {
    super(message);
    this.name = "ProtocolDecodeError";
    this.issues = issues;
  }
}

export function decodeBrowserRequest(value: unknown): BrowserRequest {
  return decode(value, validateBrowserRequest, "browser request");
}

export function decodeBrowserResponse(value: unknown): BrowserResponse {
  return decode(value, validateBrowserResponse, "browser response");
}

function decode<T>(value: unknown, validator: ProtocolValidator, role: string): T {
  if (validator(value)) {
    return value as T;
  }

  const issues = (validator.errors ?? []).map((error) =>
    \`\${error.instancePath || "/"}: \${error.message ?? error.keyword}\`,
  );
  throw new ProtocolDecodeError(\`invalid \${role}\`, issues);
}
`;
}

async function publish(filename, contents) {
  const path = resolve(generated, filename);
  if (check) {
    let current;
    try {
      current = await readFile(path, "utf8");
    } catch (error) {
      throw new Error(`cannot read generated artifact: ${path}`, { cause: error });
    }
    if (current !== contents) {
      throw new Error(`generated artifact is stale: ${path}`);
    }
    return;
  }

  await writeFile(path, contents);
}
