#!/bin/sh

entries='format=duration:stream=codec_name,pix_fmt,time_base,duration:frame=best_effort_timestamp'

if [ "$#" -ne 11 ] || \
   [ "$1" != "-v" ] || [ "$2" != "error" ] || \
   [ "$3" != "-select_streams" ] || [ "$4" != "v:0" ] || \
   [ "$5" != "-show_frames" ] || [ "$6" != "-show_entries" ] || \
   [ "$7" != "$entries" ] || \
   [ "$8" != "-of" ] || [ "$9" != "json" ] || [ "${10}" != "--" ]; then
  printf 'unexpected ffprobe arguments\n' >&2
  exit 2
fi

for argument do
  input=$argument
done

case "${input##*/}" in
  valid.mp4)
    printf '{"frames":[{"best_effort_timestamp":0},{"best_effort_timestamp":512},{"best_effort_timestamp":1024}],"streams":[{"codec_name":"h264","pix_fmt":"yuv420p","time_base":"1/15360","duration":"2.000000"}],"format":{"duration":"2.500000"}}'
    ;;
  audio.mp3)
    printf '{"frames":[],"streams":[],"format":{"duration":"2.500000"}}'
    ;;
  variable.mp4)
    printf '{"frames":[{"best_effort_timestamp":0},{"best_effort_timestamp":512},{"best_effort_timestamp":1280}],"streams":[{"codec_name":"h264","pix_fmt":"yuv420p","time_base":"1/15360","duration":"2.000000"}],"format":{"duration":"2.500000"}}'
    ;;
  still.mp4)
    printf '{"frames":[{"best_effort_timestamp":0}],"streams":[{"codec_name":"h264","pix_fmt":"yuv420p","time_base":"1/15360","duration":"2.000000"}],"format":{"duration":"2.500000"}}'
    ;;
  empty-video.mp4)
    printf '{"frames":[],"streams":[{"codec_name":"h264","pix_fmt":"yuv420p","time_base":"1/15360","duration":"2.000000"}],"format":{"duration":"2.500000"}}'
    ;;
  invalid-video-duration.mp4)
    printf '{"frames":[{"best_effort_timestamp":0},{"best_effort_timestamp":512}],"streams":[{"codec_name":"h264","pix_fmt":"yuv420p","time_base":"1/15360","duration":"N/A"}],"format":{"duration":"2.500000"}}'
    ;;
  failed.mp4)
    printf 'probe failed' >&2
    exit 7
    ;;
  failed-tail.mp4)
    index=0
    while [ "$index" -lt 1024 ]; do
      printf '0123456789abcdef' >&2
      index=$((index + 1))
    done
    printf 'final probe failure' >&2
    exit 7
    ;;
  invalid-json.mp4)
    printf 'not json'
    ;;
  missing-duration.mp4)
    printf '{"format":{}}'
    ;;
  invalid-duration.mp4)
    printf '{"format":{"duration":"N/A"}}'
    ;;
  slow.mp4)
    while :; do
      :
    done
    ;;
  large.mp4)
    index=0
    while [ "$index" -lt 8192 ]; do
      printf '0123456789abcdef'
      index=$((index + 1))
    done
    ;;
  large-stderr.mp4)
    index=0
    while [ "$index" -lt 8192 ]; do
      printf '0123456789abcdef' >&2
      index=$((index + 1))
    done
    printf '{"frames":[{"best_effort_timestamp":0},{"best_effort_timestamp":512}],"streams":[{"codec_name":"h264","pix_fmt":"yuv420p","time_base":"1/15360","duration":"1.000000"}],"format":{"duration":"1.000000"}}'
    ;;
  *)
    printf 'unexpected fixture input: %s\n' "$input" >&2
    exit 2
    ;;
esac
