// Generates runtime types and standalone validators from Rust-owned schemas.
// The Rust xtask invokes this file after publishing deterministic JSON Schema.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { compile } from "json-schema-to-typescript";

const repository = resolve(fileURLToPath(new URL("..", import.meta.url)));
const runtimeGenerated = resolve(repository, "packages/runtime/src/generated");
const bundlerGenerated = resolve(repository, "packages/bundler/src/generated");

await main(process.argv.slice(2)).catch(reportFailure);

// ── Generation pipeline

async function main(arguments_) {
  const mode = generationMode(arguments_);
  const requestSchema = await readJson(
    "schemas/browser-request-v1.schema.json",
  );
  const responseSchema = await readJson(
    "schemas/browser-response-v1.schema.json",
  );
  const bundleSchema = await readJson("schemas/bundle-manifest-v1.schema.json");

  const requestTypes = await compile(
    requestSchema,
    "BrowserRequest",
    typeOptions(),
  );
  const responseTypes = await compile(
    responseSchema,
    "BrowserResponse",
    typeOptions(),
  );
  const bundleTypes = await compile(
    bundleSchema,
    "BundleManifest",
    typeOptions(),
  );
  const bundleContract = bundleContractSource(bundleSchema, bundleTypes);
  const validators = compileValidators(requestSchema, responseSchema);

  if (mode === "write") {
    await mkdir(runtimeGenerated, { recursive: true });
    await mkdir(bundlerGenerated, { recursive: true });
  }
  await publish(mode, runtimeGenerated, "browser-request.ts", requestTypes);
  await publish(mode, runtimeGenerated, "browser-response.ts", responseTypes);
  await publish(mode, runtimeGenerated, "validators.js", validators);
  await publish(
    mode,
    runtimeGenerated,
    "validators.d.ts",
    validatorDeclarations(),
  );
  await publish(mode, runtimeGenerated, "codec.ts", codecSource());
  await publish(mode, bundlerGenerated, "bundle-manifest.ts", bundleContract);
}

function reportFailure(error) {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`protocol-codegen: ${message}\n`);
  process.exitCode = 1;
}

async function readJson(relative) {
  return JSON.parse(await readFile(resolve(repository, relative), "utf8"));
}

function generationMode(arguments_) {
  if (arguments_.length === 0) {
    return "write";
  }
  if (arguments_.length === 1 && arguments_[0] === "--check") {
    return "check";
  }
  throw new Error("usage: node scripts/protocol-codegen.mjs [--check]");
}

function typeOptions() {
  return {
    additionalProperties: false,
    bannerComment:
      "// Generated by `cargo xtask schema`; edit Rust protocol types instead.\n",
    cwd: repository,
    enableConstEnums: false,
    style: {
      bracketSpacing: true,
      printWidth: 100,
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: "all",
      useTabs: false,
    },
    unknownAny: false,
  };
}

// ── Generated sources

function compileValidators(request, response) {
  const ajv = new Ajv2020({
    allErrors: true,
    code: { esm: true, lines: true, source: true },
    // Numeric ranges are explicit in the schemas; these names register the
    // non-asserting format labels emitted by schemars.
    formats: { uint16: true, uint32: true, uint64: true },
    strict: true,
  });
  ajv.compile(request);
  ajv.compile(response);
  const source = standaloneCode(ajv, {
    validateBrowserRequest: request.$id,
    validateBrowserResponse: response.$id,
  });
  return `// Generated by \`cargo xtask schema\`; do not edit.\n${source}`;
}

function bundleContractSource(schema, types) {
  const version = schemaNumber(schema.$defs?.BundleVersion?.const, "version");
  const entryPoint = schemaString(
    schema.properties?.entryPoint?.const,
    "entry point",
  );
  const manifestFile = schemaString(
    schema["x-onmark-manifest-file"],
    "manifest file",
  );
  const assetDirectory = schemaString(
    schema["x-onmark-asset-directory"],
    "asset directory",
  );

  return `${types}
export const BUNDLE_VERSION = ${JSON.stringify(version)} as const;
export const BUNDLE_ENTRY_POINT = ${JSON.stringify(entryPoint)} as const;
export const BUNDLE_MANIFEST_FILE = ${JSON.stringify(manifestFile)} as const;
export const BUNDLE_ASSET_DIRECTORY = ${JSON.stringify(assetDirectory)} as const;
`;
}

function schemaNumber(value, name) {
  if (typeof value !== "number") {
    throw new Error(`bundle schema is missing ${name}`);
  }
  return value;
}

function schemaString(value, name) {
  if (typeof value !== "string") {
    throw new Error(`bundle schema is missing ${name}`);
  }
  return value;
}

function validatorDeclarations() {
  return `// Generated by \`cargo xtask schema\`; do not edit.
export interface ValidationError {
  readonly instancePath: string;
  readonly keyword: string;
  readonly message?: string;
}

export interface ProtocolValidator {
  (value: unknown): boolean;
  readonly errors?: readonly ValidationError[] | null;
}

export const validateBrowserRequest: ProtocolValidator;
export const validateBrowserResponse: ProtocolValidator;
`;
}

function codecSource() {
  return `// Generated by \`cargo xtask schema\`; do not edit.
import type { BrowserRequest } from "./browser-request.js";
import type { BrowserResponse } from "./browser-response.js";
import {
  validateBrowserRequest,
  validateBrowserResponse,
  type ProtocolValidator,
} from "./validators.js";

export class ProtocolDecodeError extends Error {
  readonly issues: readonly string[];

  constructor(message: string, issues: readonly string[]) {
    super(message);
    this.name = "ProtocolDecodeError";
    this.issues = issues;
  }
}

export function decodeBrowserRequest(value: unknown): BrowserRequest {
  return decode(value, validateBrowserRequest, "browser request");
}

export function decodeBrowserResponse(value: unknown): BrowserResponse {
  return decode(value, validateBrowserResponse, "browser response");
}

function decode<T>(value: unknown, validator: ProtocolValidator, role: string): T {
  if (validator(value)) {
    return value as T;
  }

  const issues = (validator.errors ?? []).map((error) =>
    \`\${error.instancePath || "/"}: \${error.message ?? error.keyword}\`,
  );
  throw new ProtocolDecodeError(\`invalid \${role}\`, issues);
}
`;
}

// ── Artifact publication

async function publish(mode, directory, filename, contents) {
  const path = resolve(directory, filename);
  if (mode === "check") {
    let current;
    try {
      current = await readFile(path, "utf8");
    } catch (error) {
      throw new Error(`cannot read generated artifact: ${path}`, {
        cause: error,
      });
    }
    if (current !== contents) {
      throw new Error(`generated artifact is stale: ${path}`);
    }
    return;
  }

  await writeFile(path, contents);
}
