// Generates runtime types and standalone validators from Rust-owned schemas.
// The Rust xtask invokes this file after publishing deterministic JSON Schema.

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import Ajv2020 from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { compile } from "json-schema-to-typescript";

const repository = resolve(fileURLToPath(new URL("..", import.meta.url)));
const runtimeGenerated = resolve(repository, "packages/runtime/src/generated");
const bundlerGenerated = resolve(repository, "packages/bundler/src/generated");

await main(process.argv.slice(2)).catch(reportFailure);

// ── Generation pipeline

async function main(arguments_) {
  const mode = generationMode(arguments_);
  const requestSchema = await readJson(
    "schemas/browser-request-v1.schema.json",
  );
  const responseSchema = await readJson(
    "schemas/browser-response-v1.schema.json",
  );
  const bundleSchema = await readJson("schemas/bundle-manifest-v2.schema.json");

  const requestTypes = await compile(
    requestSchema,
    "BrowserRequest",
    typeOptions(),
  );
  const responseTypes = await compile(
    responseSchema,
    "BrowserResponse",
    typeOptions(),
  );
  const bundleTypes = await compile(
    bundleSchema,
    "BundleManifest",
    typeOptions(),
  );
  const bundleContract = bundleContractSource(bundleSchema, bundleTypes);
  const bundleLayout = bundleLayoutSource(bundleSchema);
  const runtimeContract = runtimeContractSource(requestSchema, responseSchema);
  const validators = compileValidators(requestSchema, responseSchema);

  if (mode === "write") {
    await mkdir(runtimeGenerated, { recursive: true });
    await mkdir(bundlerGenerated, { recursive: true });
  }
  await publish(mode, runtimeGenerated, "browser-request.ts", requestTypes);
  await publish(mode, runtimeGenerated, "browser-response.ts", responseTypes);
  await publish(mode, runtimeGenerated, "validators.js", validators);
  await publish(
    mode,
    runtimeGenerated,
    "validators.d.ts",
    validatorDeclarations(),
  );
  await publish(mode, runtimeGenerated, "codec.ts", codecSource());
  await publish(mode, runtimeGenerated, "bundle-layout.ts", bundleLayout);
  await publish(mode, runtimeGenerated, "runtime-contract.ts", runtimeContract);
  await publish(mode, bundlerGenerated, "bundle-manifest.ts", bundleContract);
}

function reportFailure(error) {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`protocol-codegen: ${message}\n`);
  process.exitCode = 1;
}

async function readJson(relative) {
  return JSON.parse(await readFile(resolve(repository, relative), "utf8"));
}

function generationMode(arguments_) {
  if (arguments_.length === 0) {
    return "write";
  }
  if (arguments_.length === 1 && arguments_[0] === "--check") {
    return "check";
  }
  throw new Error("usage: node scripts/protocol-codegen.mjs [--check]");
}

function typeOptions() {
  return {
    additionalProperties: false,
    bannerComment:
      "// Generated by `cargo xtask schema`; edit Rust protocol types instead.\n",
    cwd: repository,
    enableConstEnums: false,
    style: {
      bracketSpacing: true,
      printWidth: 100,
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: "all",
      useTabs: false,
    },
    unknownAny: false,
  };
}

// ── Generated sources

function compileValidators(request, response) {
  const ajv = new Ajv2020({
    allErrors: true,
    code: { esm: true, lines: true, source: true },
    // Numeric ranges are explicit in the schemas; these names register the
    // non-asserting format labels emitted by schemars.
    formats: { uint16: true, uint32: true, uint64: true },
    // These extensions feed generated constants; JSON validation deliberately
    // treats them as non-asserting contract metadata.
    keywords: [
      "x-onmark-runtime-host",
      "x-onmark-max-failure-message-characters",
      "x-onmark-max-pending-resources",
      "x-onmark-max-pending-resource-characters",
    ],
    strict: true,
  });
  ajv.compile(request);
  ajv.compile(response);
  const source = standaloneCode(ajv, {
    validateBrowserRequest: request.$id,
    validateBrowserResponse: response.$id,
  });
  return `// Generated by \`cargo xtask schema\`; do not edit.\n${inlineUnicodeLength(source)}`;
}

function inlineUnicodeLength(source) {
  const unicodeLengthImport =
    /const ([A-Za-z_$][\w$]*) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/u;
  // AJV emits this one CommonJS helper even for ESM standalone output. Keep
  // the generated validator dependency-free while preserving code-point
  // semantics required by JSON Schema maxLength.
  const standalone = source.replace(
    unicodeLengthImport,
    "const $1 = (value) => { let length = 0; for (const _ of value) length += 1; return length; };",
  );
  if (/\brequire\s*\(/u.test(standalone)) {
    throw new Error("AJV standalone output contains a CommonJS runtime import");
  }
  return standalone;
}

function bundleContractSource(schema, types) {
  const version = schemaNumber(schema.$defs?.BundleVersion?.const, "version");
  const capabilities = schemaConstants(
    schema.$defs?.PresentationTemporalCapability?.oneOf,
    "presentation temporal capabilities",
  );
  const entryPoint = schemaString(
    schema.properties?.entryPoint?.const,
    "entry point",
  );
  const manifestFile = schemaString(
    schema["x-onmark-manifest-file"],
    "manifest file",
  );
  const assetDirectory = schemaString(
    schema["x-onmark-asset-directory"],
    "asset directory",
  );
  const capabilityTuple = typescriptTuple(capabilities);
  return `${types}
export const BUNDLE_VERSION = ${JSON.stringify(version)} as const;
export const BUNDLE_TEMPORAL_CAPABILITIES = Object.freeze(${capabilityTuple} as const);
export const BUNDLE_ENTRY_POINT = ${JSON.stringify(entryPoint)} as const;
export const BUNDLE_MANIFEST_FILE = ${JSON.stringify(manifestFile)} as const;
export const BUNDLE_ASSET_DIRECTORY = ${JSON.stringify(assetDirectory)} as const;
`;
}

function bundleLayoutSource(schema) {
  const assetDirectory = schemaString(
    schema["x-onmark-asset-directory"],
    "asset directory",
  );
  const capabilities = schemaConstants(
    schema.$defs?.PresentationTemporalCapability?.oneOf,
    "presentation temporal capabilities",
  );
  const capabilityTuple = typescriptTuple(capabilities);

  return `// Generated by \`cargo xtask schema\`; edit Rust protocol types instead.
export const BUNDLE_ASSET_DIRECTORY = ${JSON.stringify(assetDirectory)} as const;
export const PRESENTATION_TEMPORAL_CAPABILITIES = Object.freeze(${capabilityTuple} as const);
export type PresentationTemporalCapability = (typeof PRESENTATION_TEMPORAL_CAPABILITIES)[number];
`;
}

function schemaConstants(branches, name) {
  if (!Array.isArray(branches)) {
    throw new Error(`${name} must be a schema union`);
  }
  return branches.map((branch) => schemaString(branch?.const, name));
}

function typescriptTuple(values) {
  return `[\n${values.map((value) => `  ${JSON.stringify(value)},`).join("\n")}\n]`;
}

function runtimeContractSource(request, response) {
  const runtimeHost = schemaString(
    request["x-onmark-runtime-host"],
    "runtime host",
  );
  const failureMessageCharacters = schemaNumber(
    response["x-onmark-max-failure-message-characters"],
    "failure-message character limit",
  );
  const browserVideos = schemaNumber(
    request.$defs?.BrowserPlan?.properties?.videos?.maxItems,
    "browser-plan video limit",
  );
  const browserOverlays = schemaNumber(
    request.$defs?.BrowserPlan?.properties?.overlays?.maxItems,
    "browser-plan overlay limit",
  );
  const overlayTextCharacters = schemaNumber(
    request.$defs?.BrowserOverlay?.properties?.text?.maxLength,
    "browser overlay-text character limit",
  );
  const pendingResources = schemaNumber(
    response["x-onmark-max-pending-resources"],
    "pending-resource count limit",
  );
  const pendingResourceCharacters = schemaNumber(
    response["x-onmark-max-pending-resource-characters"],
    "pending-resource character limit",
  );

  return `// Generated by \`cargo xtask schema\`; edit Rust protocol types instead.
export const RUNTIME_HOST_NAME = ${JSON.stringify(runtimeHost)} as const;
export const MAX_BROWSER_VIDEOS = ${JSON.stringify(browserVideos)} as const;
export const MAX_BROWSER_OVERLAYS = ${JSON.stringify(browserOverlays)} as const;
export const MAX_BROWSER_OVERLAY_TEXT_CHARACTERS = ${JSON.stringify(overlayTextCharacters)} as const;
export const MAX_FAILURE_MESSAGE_CHARACTERS = ${JSON.stringify(failureMessageCharacters)} as const;
export const MAX_PENDING_RESOURCES = ${JSON.stringify(pendingResources)} as const;
export const MAX_PENDING_RESOURCE_CHARACTERS = ${JSON.stringify(pendingResourceCharacters)} as const;
`;
}

function schemaNumber(value, name) {
  if (typeof value !== "number") {
    throw new Error(`schema contract is missing ${name}`);
  }
  return value;
}

function schemaString(value, name) {
  if (typeof value !== "string") {
    throw new Error(`schema contract is missing ${name}`);
  }
  return value;
}

function validatorDeclarations() {
  return `// Generated by \`cargo xtask schema\`; do not edit.
export interface ValidationError {
  readonly instancePath: string;
  readonly keyword: string;
  readonly message?: string;
}

export interface ProtocolValidator {
  (value: unknown): boolean;
  readonly errors?: readonly ValidationError[] | null;
}

export const validateBrowserRequest: ProtocolValidator;
export const validateBrowserResponse: ProtocolValidator;
`;
}

function codecSource() {
  return `// Generated by \`cargo xtask schema\`; do not edit.
import type { BrowserRequest } from "./browser-request.js";
import type { BrowserResponse } from "./browser-response.js";
import {
  validateBrowserRequest,
  validateBrowserResponse,
  type ProtocolValidator,
} from "./validators.js";

export class ProtocolDecodeError extends Error {
  readonly issues: readonly string[];

  constructor(message: string, issues: readonly string[]) {
    super(message);
    this.name = "ProtocolDecodeError";
    this.issues = issues;
  }
}

export function decodeBrowserRequest(value: unknown): BrowserRequest {
  return decode(value, validateBrowserRequest, "browser request");
}

export function decodeBrowserResponse(value: unknown): BrowserResponse {
  return decode(value, validateBrowserResponse, "browser response");
}

function decode<T>(value: unknown, validator: ProtocolValidator, role: string): T {
  if (validator(value)) {
    return value as T;
  }

  const issues = (validator.errors ?? []).map((error) =>
    \`\${error.instancePath || "/"}: \${error.message ?? error.keyword}\`,
  );
  throw new ProtocolDecodeError(\`invalid \${role}\`, issues);
}
`;
}

// ── Artifact publication

async function publish(mode, directory, filename, contents) {
  const path = resolve(directory, filename);
  if (mode === "check") {
    let current;
    try {
      current = await readFile(path, "utf8");
    } catch (error) {
      throw new Error(`cannot read generated artifact: ${path}`, {
        cause: error,
      });
    }
    if (current !== contents) {
      throw new Error(`generated artifact is stale: ${path}`);
    }
    return;
  }

  await writeFile(path, contents);
}
